- id: doi:10.1093/bfgp/elae042
  description: This review paper presents recent machine learning techniques used in brain age estimation (BAE) studies.
  image: images/briefings_in_functional_genomics.png
  
- id: doi:10.1371/journal.pone.0076105
  image: https://plos.org/wp-content/uploads/2024/11/logo-plos-full-color.svg

- id: doi:10.1111/adb.12644
  image: https://onlinelibrary.wiley.com/cms/asset/86536fbd-4d9b-41ba-a451-1362f4ff3a40/adb.v24.5.cover.jpg

- id: doi:10.1002/hbm.23146
  image: https://onlinelibrary.wiley.com/cms/asset/1939df3b-05c6-4108-9fc8-93e4c59a876c/hbm.v37.5.cover.jpg

- id: doi:10.1101/2024.11.12.623073
  image: images/biorxiv_logo.png

- id: doi:10.1038/s41598-020-65086-x
  image: https://media.springernature.com/full/nature-cms/uploads/product/srep/header-d3c533c187c710c1bedbd8e293815d5f.svg

- id: doi:10.1007/s11517-013-1131-9
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/11517?as=webp

- id: doi:10.1038/srep18969
  image: https://media.springernature.com/full/nature-cms/uploads/product/srep/header-d3c533c187c710c1bedbd8e293815d5f.svg

- id: doi:10.3389/fnsys.2012.00063
  image: https://upload.wikimedia.org/wikipedia/de/thumb/3/39/Frontiers_Media_logo.svg/1600px-Frontiers_Media_logo.svg.png?20240304013843

- id: doi:10.1016/j.neuropsychologia.2020.107549
  image: https://ars.els-cdn.com/content/image/X00283932.jpg

- id: doi:10.1007/s11682-016-9597-3
  image: https://media.springernature.com/w230/springer-static/cover/journal/11682/11/1.jpg?as=webp

- id: doi:10.1007/s00330-016-4221-x
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/330?as=webp

- id: doi:10.1155/2016/9849087
  image: https://onlinelibrary.wiley.com/cms/asset/be23627c-d051-4327-ae27-69b9c7a90ede/default_cover.jpg

- id: doi:10.1038/s41598-017-04148-z
  image: https://media.springernature.com/full/nature-cms/uploads/product/srep/header-d3c533c187c710c1bedbd8e293815d5f.svg

- id: doi:10.3389/fnhum.2017.00473
  image: https://upload.wikimedia.org/wikipedia/de/thumb/3/39/Frontiers_Media_logo.svg/1600px-Frontiers_Media_logo.svg.png?20240304013843

- id: doi:10.1016/j.jneumeth.2015.08.006
  image: https://ars.els-cdn.com/content/image/X01650270.jpg

- id: doi:10.1007/978-3-642-35428-1_14
  image: https://media.springernature.com/w316/springer-static/cover-hires/book/978-3-642-35428-1?as=webp

- id: doi:10.1109/EMBC.2016.7591617
  image: images/EMBC16.png

- id: doi:10.1016/bs.acr.2024.06.005
  authors:
  - Lusheng Li
  - Mengtao Sun
  - Jieqiong Wang
  - Shibiao Wan
  image: https://ars.els-cdn.com/content/image/X0065230X.jpg

- id: doi:10.1117/12.2217308
  image: https://spie.org/Images/Graphics/ConferenceLogo/mi.svg

- id: doi:10.3390/biom14040409
  image: https://pub.mdpi-res.com/img/journals/biomolecules-logo.png?8600e93ff98dbf14

- id: doi:10.1117/12.2216647
  image: https://spie.org/Images/Graphics/ConferenceLogo/mi.svg

- id: doi:10.1117/12.2043424
  image: https://spie.org/Images/Graphics/ConferenceLogo/mi.svg

- id: doi:10.3389/fgene.2023.1256468
  image: https://curehht.org/wp-content/uploads/2017/11/Frontiers-in-Genetics-logo.png

- id: 10.1093/bfgp/elae046
  image: images/briefings_in_functional_genomics.png
  
- id: doi:10.1007/978-3-319-68843-5_10
  image: https://media.springernature.com/lw150/springer-static/cover-hires/series/8578?as=webp

- id: doi:10.1109/APSAR.2009.5374134
  authors:
  - Xin Lu
  - Jieqiong Wang
  - Zhenghuan Wang
  - Hong Sun
  image: images/APSAR.png

- id: doi:10.1158/1538-7445.AM2024-4907
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/84/6_supplement/1/m_canres_84_6_cover.png?Expires=1745374425&Signature=btHABNE70oAhzM98ad70aidAIRoUlJQYLAFtTp2dbUICTl-qqJQEuysdCTMg7-90Ctxj9UK3RuXcPyJIAVtnjNOK6DeG6OvzdII4DUjpYdkw9QZ1wDOyLDXxWcG3MkOdhjq6RI8fTrHMboy4pwsdHR05SRU3URu9G2njBcGYDe0vYO5PYsxD61e7WkcXinGyYbMeHnHROF9uDoe9xwPH4Slm7nPSvPPJGDtNcvkzKejoR-3fzjnHhsCQNvWadEV-We44E58DzOEgLzpBkF8MjK-fbM-7aAFpLEKRBOnaYGMVUfR26hRoM3Boig8Wue~dsPDC8yWdN2Ht4YliA7csgQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.3389/fonc.2023.1125186
  image: https://www.frontiersin.org/files/Taxonomy/2935.JPEG

- id: doi:10.3389/fgene.2022.876686
  image: https://curehht.org/wp-content/uploads/2017/11/Frontiers-in-Genetics-logo.png

- id: doi:10.1101/2024.09.25.614862
  image: images/biorxiv_logo.png

- id: doi:10.1101/2024.09.24.614777
  image: images/biorxiv_logo.png

- id: doi:10.1002/hbm.70013
  image: https://onlinelibrary.wiley.com/cms/asset/8309db05-5460-4ca3-a779-d97319129b33/hbm.v45.13.cover.jpg

- id: doi:10.1158/1538-7445.AM2024-4800
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/84/6_supplement/1/m_canres_84_6_cover.png?Expires=1745374425&Signature=btHABNE70oAhzM98ad70aidAIRoUlJQYLAFtTp2dbUICTl-qqJQEuysdCTMg7-90Ctxj9UK3RuXcPyJIAVtnjNOK6DeG6OvzdII4DUjpYdkw9QZ1wDOyLDXxWcG3MkOdhjq6RI8fTrHMboy4pwsdHR05SRU3URu9G2njBcGYDe0vYO5PYsxD61e7WkcXinGyYbMeHnHROF9uDoe9xwPH4Slm7nPSvPPJGDtNcvkzKejoR-3fzjnHhsCQNvWadEV-We44E58DzOEgLzpBkF8MjK-fbM-7aAFpLEKRBOnaYGMVUfR26hRoM3Boig8Wue~dsPDC8yWdN2Ht4YliA7csgQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1101/2025.02.24.640010
  image: images/biorxiv_logo.png

- id: doi:10.1200/JCO.2025.43.5_suppl.242
  image: https://ascopubs.org/action/showCoverImage?journalCode=jco&imgSize=small

- id: doi:10.1158/1538-7445.AM2025-5016
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1158/1538-7445.AM2025-6314
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1158/1538-7445.AM2025-3620
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1158/1538-7445.AM2025-1098
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.48550/arXiv.2504.17162
  image: images/arxiv-logo.png
  date: '2025-04-24'
  
- id: doi:10.1158/1538-7445.AM2025-1104
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1158/1538-7445.AM2025-7425
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1158/1538-7445.AM2025-5022
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/85/8_supplement_1/1/m_canres_85_8_supplement_1_cover.jpeg?Expires=1749086961&Signature=u5nAYKv7kIWhrYesW~JmkHTzokTOA5hrpyJbfwJXqCxThaL9~2R~7Lo1c0vM3aGzmQgyxJsSuwp5lmREt-3tqN4mZGooJQbeqSzB7elJ2kDiG-AIhsfWCRVdut~XeL~QfwStBxdTEE3mCPjYjdxL~59HuYOkMG1FP8luJmiipLkf1FBNG-lpXP56wqlvGt3pUAR-kcTicE8kruGTGMcQEZAoLjxqGLaUHYjAm4ewbJg9be0~LJcDeZQ4DxDGQfJ~5xy0FNOpYObtfOD~grTsVGBYDVDVyfuu4ZE9gP2iMB5luXv1hdLfcG-4u2DiqjlAV6kuVSUpbH1KUOIOSvNW9Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1101/2025.05.01.651699
  image: images/biorxiv_logo.png

- id: doi:10.1101/2025.05.20.655179
  image: images/biorxiv_logo.png

- id: doi:10.48550/arXiv.2505.09105
  image: images/arxiv-logo.png
  date: '2025-05-14'

- id: doi:10.1002/aisy.202500635
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/ef1af8a6-3ecb-4aa9-a63b-7f8be93bf14d/aisy.v7.9.cover.gif
  
- title: 'nnU-BNST: Deep Learning-Based Automated Segmentation of the Bed Nucleus of the Stria Terminalis'
  authors:
  - Ziyang Xu
  - Mohamed Azzam
  - Marshall Bivens
  - Marcus Dustin
  - Shibiao Wan
  - Jennifer Urbano Blackford
  - Jieqiong Wang
  publisher: Lecture Notes in Computer Science
  date: '2025-09-23'
  image: https://media.springernature.com/full/springer-static/cover-hires/book/978-3-032-09512-1?as=webp

- id: 10.64898/2025.12.15.694538
  image: images/biorxiv_logo.png

- id: 10.64898/2025.12.22.696111
  image: images/biorxiv_logo.png
  
